//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoAssetManagement.StockScreener.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public string Symobl { get; set; }
        public System.DateTime RecordDate { get; set; }
        public Nullable<decimal> BookValue { get; set; }
        public Nullable<decimal> DividendShare { get; set; }
        public Nullable<decimal> EarningsShare { get; set; }
        public Nullable<decimal> EPSEstimateCurrentYear { get; set; }
        public Nullable<decimal> EPSEstimateNextYear { get; set; }
        public Nullable<decimal> EPSEstimateNextQuarter { get; set; }
        public Nullable<decimal> YearLow { get; set; }
        public Nullable<decimal> YearHigh { get; set; }
        public Nullable<decimal> MarketCapitalization { get; set; }
        public Nullable<decimal> EBITDA { get; set; }
        public Nullable<decimal> PercentChangeFromTwoHundreddayMovingAverage { get; set; }
        public Nullable<decimal> PercentChangeFromFiftydayMovingAverage { get; set; }
        public Nullable<decimal> PriceSales { get; set; }
        public Nullable<decimal> PriceBook { get; set; }
        public Nullable<decimal> PERatio { get; set; }
        public Nullable<decimal> PEGRatio { get; set; }
        public Nullable<decimal> PriceEPSEstimateCurrentYear { get; set; }
        public Nullable<decimal> PriceEPSEstimateNextYear { get; set; }
        public Nullable<decimal> ShortRatio { get; set; }
        public Nullable<decimal> OneyrTargetPrice { get; set; }
    }
}
