//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoAssetManagement.StockScreener.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string ExchangeSymbol { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public string IndustrySectorFeed { get; set; }
    
        public virtual Exchange Exchange { get; set; }
        public virtual Industry Industry { get; set; }
    }
}
